version: "3.2"

services:
  app:
    build:
      context: .
    image: &app app
    env_file: &envfile
      - env.env
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - broker

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6384:6379"

  broker:
    image: rabbitmq:3
    env_file: *envfile
    ports:
      - 5672:5672
